config/routes.rb
Rails.application.routes.draw do

  get 'reviews/new'

  get 'reviews/index'

  get 'reviews/show'

  resources :cocktails do
    resources :doses, only: [ :new, :create ]
  end

  resources :doses, only: [ :destroy ]

  get '/cocktails/:id/upload', to: 'cocktails#upload', as: 'upload_photo'

  post '/cocktails/:id', to: 'cocktails#update'

  get 'cocktails/:cocktail_id/reviews/new', to: "reviews#new", as: 'new_review'

  post 'cocktails/:cocktail_id/reviews', to: "reviews#create", as: 'cocktail_reviews'

  get 'reviews/:id', to: "reviews#show"

  get 'cocktails/:cocktail_id/reviews', to: "reviews#index", as: 'all_reviews'

  root "cocktails#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :ingredients, through: :doses
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  # validates_uniqueness_of :ingredient, through: :cocktail
  belongs_to :cocktail
  belongs_to :ingredient

  DOSES = ["a pinch of", "a dash of", "a spoonful of", "a dollop of", "a whole lotta"]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [ :show, :edit, :upload, :update, :destroy ]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def upload
  end

  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'Your cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_cocktail, only: [:new, :create, :index]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    @review.save!
    redirect_to cocktails_path
  end

  def show
    @review = Review.find(params[:id])
  end

  def index
    @reviews = Review.where(cocktail_id: @cocktail.id)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def review_params
    params.required(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form-photo.html.erb
<div class="container text-center form-stuff">
  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= link_to "Nevermind", cocktails_path, class: "btn btn-pink" %>&nbsp;
    <%= f.submit "Upload Photo", class: "btn btn-pink" %>
  <% end %>
</div>

app/views/cocktails/_form.html.erb
<div class="container text-center form-stuff">
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name, input_html: { placeholder: "Cosmic Concoction" } %>
    <%= link_to "Nevermind", cocktails_path, class: "btn btn-pink" %>&nbsp;<%= f.submit class: "btn btn-pink" %>
  <% end %>
</div>

app/views/cocktails/edit.html.erb
<h1>Edit a Cocktail</h1>
<%= render "form" %>

app/views/cocktails/index.html.erb
<h1><%= image_tag "potion.png", width: 80 %>&nbsp;&nbsp;Creepy Cocktails&nbsp;&nbsp;<%= image_tag "potion.png", width: 80 %></h1>
<br>
<p><%= link_to "Create Cocktail", new_cocktail_path, class: "btn btn-pink" %></p>
<div class="container text-center content-box">
  <% @cocktails.each do |cocktail| %>
  <div class="row card">
    <h2><%= cl_image_tag cocktail.photo.url, height: 100, width: 100, crop: :scale, class: "img-circle" %>&nbsp;&nbsp;&nbsp;<%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
  </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<h1>Create Your Own Cocktail</h1>
<br>
<%= render "form" %>

app/views/cocktails/show.html.erb
<div class="container text-center content-box">
  <div class="row card">
    <h2><%= @cocktail.name %></h2>
    <%= cl_image_tag @cocktail.photo.url, height: 100, width: 100, crop: :scale, class: "img-circle" %>
    <ul>
      <% @cocktail.doses.each do |dose| %>
        <li><%= "#{dose.description} #{dose.ingredient.name}" %></li>
      <% end %>
    </ul>
    <%= link_to "Add Ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-pink" %>
    &nbsp;
    <%= link_to "Add Photo", upload_photo_path(@cocktail), class: "btn btn-pink" %>
    <br>
    <%= link_to "Write Comment", new_review_path(@cocktail), class: "btn btn-pink" %>
    &nbsp;
    <%= link_to "Delete", cocktail_path(@cocktail), method: :delete, class: "btn btn-pink" %>
    &nbsp;
    <%= link_to "Home", cocktails_path, class: "btn btn-pink" %>
  </div>
  <% @cocktail.reviews.each do |review| %>
    <div class="row card" id="comment-box">
      <%= review.content %>
    </div>
  <% end %>
</div>

app/views/cocktails/upload.html.erb
<h1>Upload a Photo</h1>
<br>
<%= render "form-photo" %>

app/views/doses/_form.html.erb
<div class="container text-center form-stuff">
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description, as: :select, collection: Dose::DOSES, include_blank: "Select dosage" %>
    <%= f.input :ingredient_id, as: :select, collection: Ingredient.order(:name), include_blank: "Select ingredient" %>
    <%= link_to "Nevermind", cocktails_path, class: "btn btn-pink" %>&nbsp;<%= f.submit "Add Ingredient", class: "btn btn-pink" %>
  <% end %>
</div>

app/views/doses/new.html.erb
<h1>Choose Dose and Ingredient</h1>
<br>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Creepy Cocktails</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<div class="container text-center form-stuff">
  <%= simple_form_for [@cocktail, @review] do |f| %>
    <%= f.input :content, input_html: { placeholder: "type comment here" } %>
    <%= link_to "Nevermind", cocktail_path(@cocktail), class: "btn btn-pink" %>&nbsp;<%= f.submit "Add Comment", class: "btn btn-pink" %>
  <% end %>
</div>

app/views/reviews/index.html.erb
<h1>Comments</h1>
<div class="container text-center content-box">
  <% @reviews.each do |review| %>
  <div class="row card">
    <p><%= review.content %></p>
  </div>
  <% end %>
  <br>
  <%= link_to "Write Comment", new_review_path(@cocktail), class: "btn btn-pink" %>&nbsp;<%= link_to "Back", cocktail_path(@cocktail), class: "btn btn-pink" %>
</div>

app/views/reviews/new.html.erb
<h1>Write a Comment</h1>
<br>
<%= render "form" %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>